### ISSUE TITLE
Simple usage examples?

### ISSUE THREAD

**Issue by DennisHeimbigner** [awslabs/aws-c-s3#146]
Is there anywhere a set of simple examples for using aws-c-s3?
The tests seem overly complex. It would be nice to have
examples showing how to read an object, write an object, and list a bucket.

**Comment by TingDaoK** [comment]
From the C land, yeah, it's complicated to set it up. 
We have interfaces binding out to java, and sample can be found [here](https://github.com/awslabs/aws-crt-java/blob/main/src/test/java/com/amazonaws/s3/S3NativeClientTest.java)
And for python, samples can be found from s3transfer https://github.com/boto/s3transfer/blob/develop/tests/integration/test_crt.py.
Also, we integrated with AWS CLI v2 as an experimental feature. https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#preferred-transfer-client

**Comment by DennisHeimbigner** [comment]
Sigh, thanks.

**Comment by DennisHeimbigner** [comment]
BTW where can the source code for the CLI experiment?

**Comment by TingDaoK** [comment]
The source code of CLI is complicated with multiple layers. https://github.com/aws/aws-cli/commit/417eeddebae24107ed52375275031e617e4ea9ff You can start with here to dig into it if you want.

**Comment by DennisHeimbigner** [comment]
I see. Also, I did not realize that CLI is python.
If at some point someone does do something using C,
please let me know.

**Comment by graebm** [comment]
A sample has been added. It's a CLI application that can `ls` an S3 bucket, `cp` from S3 bucket to filesystem, or `cp` from filesystem to S3 bucket.

https://github.com/awslabs/aws-c-s3/tree/main/samples/s3
