### ISSUE TITLE
aws-c-s3: client-configured is not released at time of client destruction

### ISSUE THREAD

**Issue by grrtrr** [awslabs/aws-c-s3#176]
_This problem occurs when passing an `aws_s3_client_config.retry_strategy` into the s3 client._

### Problem description

The `aws_retry_strategy_new_[...]()` functions all initialize the `retry_strategy` `ref_count` to 1,
which is then used in `s_s3_client_finish_destroy_default` to destroy the `retry_strategy`.

For client-configured retry strategies, however, _reference counting is handled differently_:
- client configured retry strategies also get initialized with a `ref_count` of 1,
- but they get an additional increase by 1 in `aws_s3_client_new`:
```c
// source/s3_client.c
struct aws_s3_client *aws_s3_client_new(
    struct aws_allocator *allocator,
    const struct aws_s3_client_config *client_config) {

    if (client_config->retry_strategy != NULL) {
        aws_retry_strategy_acquire(client_config->retry_strategy);  // <== HERE
        client->retry_strategy = client_config->retry_strategy;     // <== INITIAL REF COUNT IS NOW 2
    } else {
        struct aws_exponential_backoff_retry_options backoff_retry_options = {
            .el_group = client_config->client_bootstrap->event_loop_group,
            .max_retries = s_default_max_retries,
        };

        struct aws_standard_retry_options retry_options = {
            .backoff_retry_options = backoff_retry_options,
        };

        client->retry_strategy = aws_retry_strategy_new_standard(allocator, &retry_options);  // <== INITIAL REF COUNT = 1
    }
}
```
**_As a result, the `client-retry_strategy` is never released in `s_s3_client_finish_destroy_default`, causing the code to hang._**

**Comment by TingDaoK** [comment]
Whoever creates the `retry_strategy` holds one refcount to it and being responsible to release it when not needed anymore.

So, if the user create their own `retry_strategy` and pass it in as part of the `client_config`, they will need to release the refcount after `client_config` used.

The client will hold one refcount to keep it alive during the lifetime of the client. I don't see any issue here.

**Comment by grrtrr** [comment]
So is _order_ of what you are suggesting this:
```c++
void S3CrtClient::init(const S3Crt::ClientConfiguration& config, const Aws::Auth::AWSCredentials* credentials)
{
 // ...
  s3CrtConfig.retry_strategy = aws_retry_strategy_new_exponential_backoff(Aws::get_aws_allocator(), &retry_options);
  m_s3CrtClient = aws_s3_client_new(Aws::get_aws_allocator(), &s3CrtConfig);
  if (tlsConnectionOptions)
  {
    aws_tls_connection_options_clean_up(&tlsOptions);
  }
  if (!m_s3CrtClient)
  {
    AWS_LOGSTREAM_FATAL(ALLOCATION_TAG, "Failed to allocate aws_s3_client instance, abort.");
  }
  aws_retry_strategy_release(s3CrtConfig.retry_strategy);
}
```

**Comment by TingDaoK** [comment]
yeah. If the CPP implementation missed the `aws_retry_strategy_release(s3CrtConfig.retry_strategy);`, it's a bug from there.

**Comment by TingDaoK** [comment]
Feel like if there is a destructor for `s3CrtConfig`, the `aws_retry_strategy_release(s3CrtConfig.retry_strategy);` should happen from the destructor instead. 

Anyway, close the issue as it's not an issue for this repo. Sounds like an issue for C++ SDK. Feel free to tag me if you create a new issue there.
