### ISSUE TITLE
Upload to S3

### ISSUE THREAD

**Issue by martinpeniak** [awslabs/aws-c-s3#193]
Hi,

Thanks for this work. I am trying to understand what would be the simplest way to upload a file to S3.
I have seen your samples but that is a bit more elaborated and looks like it's using command line arguments and then relevant aws functions to process these. However, I simply want to use C++ to upload a file to S3 without all the extra complexities.

Do you have example for this please?

Thank you

**Comment by TingDaoK** [comment]
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3.html

**Comment by TingDaoK** [comment]
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-objects.html This seems to be a better link
