### ISSUE TITLE
Hard-coded Host header domain in aws_s3_get_object_size_message_new

### ISSUE THREAD

**Issue by bpiper** [awslabs/aws-c-s3#206]
I believe this is responsible for an object metadata request failing when trying to copy objects using the AWS Java SDK v2 Transfer Manager API (and presumably for other clients using this library).  I raised https://github.com/aws/aws-sdk-java-v2/issues/3370 initially, then tracked the problem to the changes introduced in #166 .

The object metadata request will fail if talking to a local Minio server, e.g. the endpoint specified is `localhost:9100`, in theory the Host header value should be `my-bucket.localhost:9100` (as it is for other SDK client requests), but is actually `my-bucket.s3.us-west-2.amazonaws.com`, to which Minio will understandably respond with a 404.  I don't know if this also fails when talking to Amazon S3 for regions other than us-west-2.

I'm not familiar enough with this code (and haven't touched C in too long) to offer a solution, but perhaps @cmello or someone else could take a look.  No doubt the actual request endpoint is readily available somewhere and can be used to construct the Host header value.

**Comment by yasminetalby** [comment]
Hello @bpiper ,

I will be closing this issue as the original issue has been resolved. If you have any further inquiries or question please let me know!

Best regards, 

Yasmine
