### ISSUE TITLE
FreeBSD port: testunit fails

### ISSUE THREAD

**Issue by nunotexbsd** [awslabs/aws-c-s3#212]
poudriere interactive [jail](https://people.freebsd.org/~eduardo/logs/aws-c-s3/aws-c-s3-0.1.47_1.log) for:
```
package name: aws-c-s3-0.1.47_1
building for: FreeBSD 131amd64-devel 13.1-RELEASE FreeBSD 13.1-RELEASE amd64

-- The C compiler identification is Clang 13.0.0

```
`make test`:
```
(...)
174 - test_s3_copy_source_prefixed_by_slash (Failed)
        175 - test_s3_copy_source_prefixed_by_slash_multipart (Failed)
        178 - test_s3_list_bucket_valid (Failed)
Errors while running CTest
Output from these tests are in: /wrkdirs/usr/ports/devel/aws-c-s3/work/.build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
FAILED: CMakeFiles/test.util
cd /wrkdirs/usr/ports/devel/aws-c-s3/work/.build && /usr/local/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
*** Error code 1

ctest --force-new-ctest-process --rerun-failed --output-on-failure
```
Results:
 - [LastTestsFailed.log](https://people.freebsd.org/~eduardo/logs/aws-c-s3/LastTestsFailed.log)
 - [LastTest.log](https://people.freebsd.org/~eduardo/logs/aws-c-s3/LastTest.log)

Thanks

**Comment by nunotexbsd** [comment]
https://github.com/aws/s2n-tls/issues/3489 have fixed tests on s3n-tls, could you please take a look?

**Comment by TingDaoK** [comment]
> ***FAILURE*** Failing test because the operation failed with error aws-c-auth: AWS_AUTH_SIGNING_NO_CREDENTIALS, Attempt to sign an http request without credentials

The error message indicates that you don't have proper AWS credentials setup on your machine. And also, please refer to [here](https://github.com/awslabs/aws-c-s3/tree/main/tests/test_helper) about the pre-requirement for running the tests.

**Comment by nunotexbsd** [comment]
@TingDaoK

Thanks for the hint! I missed that.

Since this tests are an optional feature for this port, using `ENABLE_NET_TESTS OFF` fixes it: `100% tests passed, 0 tests failed out of 45`. 

Cheers
