### ISSUE TITLE
[Feature Request]: support for multi-part byte ranges

### ISSUE THREAD

**Issue by grrtrr** [awslabs/aws-c-s3#257]
## Rationale

The `aws-c-s3` library already supports ranged-GET for doing single [`byte-range`](https://www.rfc-editor.org/rfc/rfc9110.html#name-byte-ranges) requests in parallel.

The s3 backend supports single byte-ranges, but not [`multipart/byteranges`](https://www.rfc-editor.org/rfc/rfc9110.html#name-media-type-multipart-bytera) as the following experiment shows.

#### 1. Single range

For a `Range` header containing `bytes=0-499`, the server responds with
```console
ETag: "adca0407e42a4f8b1caea85350a8d2ce-5"
Accept-Ranges: bytes
Content-Range: bytes 0-499/74153027
Content-Type: application/octet-stream
ServerAmazon: S3
Content-Length: 500

Response code: 206
```

#### 2. Multiple ranges

To a  `Range` header containing `bytes=0-499,500-502` the server responds with
```console
ETag:"adca0407e42a4f8b1caea85350a8d2ce-5"
Accept-Ranges: bytes
Content-Type: application/octet-stream
ServerAmazon: S3
Content-Length: 74153027

Response code: 200
```

The absence of the `Content-Range` header and the response code (different from 206) indicate that the backend _does not support_ this [optional](https://www.rfc-editor.org/rfc/rfc9110.html#name-range-requests) feature.

_Retrieving multiple ranges within a call is very useful, in particular when only a few selected ranges (e.g. chunks) of a large/huge blob are required. This saves round-trip-times and hence speeds up processing._

## Proposed feature being asked for

Multipart byte ranges can be emulated on the client side by the `aws-c-s3` library by e.g.
- assigning a single `meta_request` to the emulated `multipart/byteranges` transfer,
- splitting the multiple byte-ranges into separate requests,
- re-assembling the result into a [`multipart/byteranges`](https://www.rfc-editor.org/rfc/rfc9110.html#name-media-type-multipart-bytera) response.

**Comment by yasminetalby** [comment]
Hello @grrtrr ,

Thank you very much for your detailed submission and request. My apologies for the delay of answer on this issue. 

After discussion with the team we have decided to not implement this feature as it is currently not supported by the service.
I will close this issue, if you have any further inquiries please let me know.

Best regards,

Yasmine
