### ISSUE TITLE
Issue about possible mistake "bad copypast"

### ISSUE THREAD

**Issue by Bbulatov** [awslabs/aws-c-s3#357]
### Describe the bug

Hello!
During the static analysis process, a suspicion of a bad copypast error was identified in s3_util.c:208. There is no changes between two blocks (192-196 and 208-214 lines), but in 192 and 208 lines the same instruction: "if (signing_config->service.len > 0) {". I think there should be signed_body_value instead of service in line 208.Please clarify is this right? 

### Expected Behavior

In line 208:
if (signing_config->signed_body_value.len > 0) {

### Current Behavior

In line 208:
if (signing_config->service.len > 0) {

### Reproduction Steps

This occurs when calling

struct aws_cached_signing_config_aws *aws_cached_signing_config_new(
    struct aws_allocator *allocator,
    const struct aws_signing_config_aws *signing_config)

### Possible Solution

Change "if (signing_config->service.len > 0) {" to "if (signing_config->signed_body_value.len > 0) {"

### aws-c-s3 version used

v0.3.18

### Compiler and version used

g++ 8.3.0

### Operating System and version

OS Linux Debian

**Comment by waahm7** [comment]
Thank you for creating the issue. We have fixed it in https://github.com/awslabs/aws-c-s3/releases/tag/v0.3.19.
