### ISSUE TITLE
Build broken since #360

### ISSUE THREAD

**Issue by snickl** [awslabs/aws-c-s3#378]
### Describe the bug

#360 introduced AWS_ERROR_HTTP_RESPONSE_FIRST_BYTE_TIMEOUT and others, which aren't defined

### Expected Behavior

Package compiles

### Current Behavior

Does not compile

### Reproduction Steps

Compile package

### aws-c-s3 version used

0.3.23..0.4.0

### Compiler and version used

gcc 12

### Operating System and version

debian 11 / buildroot 2023.08

**Comment by jmklix** [comment]
Can you provide more details about this? What errors are you seeing when you try to build? and what steps are you using to build?

**Comment by waahm7** [comment]
You need to ensure that the dependencies (aws-c-* packages like aws-c-http, aws-c-common, etc.) are also updated to the latest version.

**Comment by snickl** [comment]
I'm packaging aws-iot-device-sdk-cpp-v2 and aws-iot-fleetwise-edge for buildroot, using the latest versions of each package as I've moved down the dependency chain.
It seems the cmake package dependencies are all satisfied, and I haven't seen a missing header error.
What package/header is supposed to provide AWS_ERROR_HTTP_RESPONSE_FIRST_BYTE_TIMEOUT et.al.?

**Comment by DmitriyMusatkin** [comment]
AWS_ERROR_HTTP_RESPONSE_FIRST_BYTE_TIMEOUT should be defined in the latest release of aws-c-http

**Comment by snickl** [comment]
> AWS_ERROR_HTTP_RESPONSE_FIRST_BYTE_TIMEOUT should be defined in the latest release of aws-c-http

You're right. So there's at least one package I must have missed when switching on release notifications...
