### ISSUE TITLE
Support machines with multiple NICs

### ISSUE THREAD

**Issue by graebm** [awslabs/aws-c-s3#415]
### Describe the feature

AWS has a [growing list](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#network-cards) of instance types with multiple NICs. There should be some way to configure the S3 client to use a particular network interface (or multiple network interfaces?)

### Use Case

Maximum throughput cannot be achieved with all instances of the S3 client using just the one default network interface.

### Proposed Solution

* S3 client takes IP of network interface to bind its connections to
* If multiple IPs passed, the S3 client distributes connections among them all

### Other Information

Mountpoint (which uses aws-c-s3) recently received this feature request: https://github.com/awslabs/mountpoint-s3/issues/815

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jmklix** [comment]
https://github.com/awslabs/aws-c-io/pull/467

**Comment by waahm7** [comment]
This is now supported through https://github.com/awslabs/aws-c-s3/blob/main/include/aws/s3/s3_client.h#L552.
